version: "3.8"
services:
  python_app:
    image: python:3.9-slim-buster
    volumes:
      - ./:/app
    command: bash -c "cd /app && pip install -r requirements.txt && python3 app.py && tail -f /dev/null"